version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    reviewers:
      - 'saharshy29'
    assignees:
      - 'saharshy29'
    open-pull-requests-limit: 10
    rebase-strategy: 'auto'
    commit-message:
      prefix: "⬆️dependabot:"
